### ISSUE TITLE
vue登录后调用后端接口报错

### ISSUE THREAD

**Issue by lianglinux5** [Exrick/xboot#17]
前端登录后报错
java.lang.ClassNotFoundException: cn.exrick.xboot.entity.User

**Comment by Exrick** [comment]
是否改过代码 后端是否启动成功 在线文档 https://www.kancloud.cn/exrick/xboot/content

**Comment by lianglinux5** [comment]
从github上重新迁出代码好了

**Comment by duanshuyong0** [comment]
> 从github上重新迁出代码好了

从新checkout 就好了吗  我也遇到了这个错

**Comment by Exrick** [comment]
@duanshuyong0 若更新代码 请记得重新导入sql并清空Redis

**Comment by duanshuyong0** [comment]
> @duanshuyong0 若更新代码 请记得重新导入sql并清空Redis

非常感谢，重新导入后可以了
