### ISSUE TITLE
多模块打包时报错

### ISSUE THREAD

**Issue by ttnkh21** [Exrick/xboot#36]
"D:\Program Files\JetBrains\IntelliJ IDEA 2019.3\jbr\bin\java.exe" -Dmaven.multiModuleProjectDirectory=D:\angular\xboot-master2\xboot-module\xboot-admin "-Dmaven.home=D:\Program Files\JetBrains\IntelliJ IDEA 2019.3\plugins\maven\lib\maven3" "-Dclassworlds.conf=D:\Program Files\JetBrains\IntelliJ IDEA 2019.3\plugins\maven\lib\maven3\bin\m2.conf" "-Dmaven.ext.class.path=D:\Program Files\JetBrains\IntelliJ IDEA 2019.3\plugins\maven\lib\maven-event-listener.jar" "-javaagent:D:\Program Files\JetBrains\IntelliJ IDEA 2019.3\lib\idea_rt.jar=51179:D:\Program Files\JetBrains\IntelliJ IDEA 2019.3\bin" -Dfile.encoding=UTF-8 -classpath "D:\Program Files\JetBrains\IntelliJ IDEA 2019.3\plugins\maven\lib\maven3\boot\plexus-classworlds-2.6.0.jar" org.codehaus.classworlds.Launcher -Didea.version2019.3 compile
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'parent.relativePath' of POM cn.exrick:xboot-admin:1.0-SNAPSHOT (D:\angular\xboot-master2\xboot-module\xboot-admin\pom.xml) points at cn.exrick:xboot-module instead of cn.exrick:xboot-modules, please verify your project structure @ line 5, column 13
[FATAL] Non-resolvable parent POM for cn.exrick:xboot-admin:1.0-SNAPSHOT: Could not find artifact cn.exrick:xboot-modules:pom:1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project cn.exrick:xboot-admin:1.0-SNAPSHOT (D:\angular\xboot-master2\xboot-module\xboot-admin\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for cn.exrick:xboot-admin:1.0-SNAPSHOT: Could not find artifact cn.exrick:xboot-modules:pom:1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by Exrick** [comment]
根pom.xml添加指定插件版本
```xml
<build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring.boot.version}</version>
            </plugin>
        </plugins>
    </build>
```

**Comment by Exrick** [comment]
更新代码 已修复
