### ISSUE TITLE
多模块版本打包 pom报错

### ISSUE THREAD

**Issue by ttnkh21** [Exrick/xboot#38]
dependencies
Could not find artifact cn.exrick:xboot-module:pom:1.0-SNAPSHOT
[ERROR] Some problems were encountered while processing the POMs:
The build could not read 1 project

**Comment by Exrick** [comment]
叫你更新代码 @ttnkh21

**Comment by ttnkh21** [comment]
@Exrick 就是更新过的，还是这个错误

**Comment by Exrick** [comment]
清空maven mvn clean
重新install尝试
