### ISSUE TITLE
不吐不快 多模块版本编译报错 作者一直也没有解决

### ISSUE THREAD

**Issue by ttnkh21** [Exrick/xboot#40]
运行没问题，但是没法编译，需要把各个模块重新拆分组合后才可以，目前这种组合方式 编译时一直报如下错误
Could not find artifact cn.exrick:xboot-module:pom:1.0-SNAPSHOT
[ERROR] Some problems were encountered while processing the POMs:
The build could not read 1 project

**Comment by Exrick** [comment]
亲 麻烦更新代码 很久之前解决了的 之前artifactid写错了
还有问题麻烦加群远程解决

**Comment by ttnkh21** [comment]
刚刚拉取的最新版代码

**Comment by Exrick** [comment]
- 这边也是刚拉取代码测试没问题哦

<img src=https://i.loli.net/2020/03/13/dHL3Wm1PN4eAatK.png>

- 先根目录下执行`mvn install`，然后进入`xboot-admin`入口模块执行`mvn spring-boot:run`
```shell
mvn install
cd xboot-admin
mvn spring-boot:run
```
https://www.kancloud.cn/exrick/xboot/1425010

**Comment by ttnkh21** [comment]
![image](https://user-images.githubusercontent.com/23454757/76599675-71d02480-6540-11ea-8507-1c86b63d3472.png)

**Comment by ttnkh21** [comment]
也是刚刚重新拉取的代码，根目录运行 mvn install报错，运行mvn package也报错

**Comment by ttnkh21** [comment]
![image](https://user-images.githubusercontent.com/23454757/76599846-c1165500-6540-11ea-919a-134d6cb4bca6.png)

**Comment by Exrick** [comment]
有尝试mvn clean吗

**Comment by ttnkh21** [comment]
![image](https://user-images.githubusercontent.com/23454757/76681679-8855a900-6630-11ea-806e-276f3d8af398.png)
------同样的错误------

**Comment by Exrick** [comment]
请按照如下命令执行，模块结构没有问题，还有问题请加群找群主远程
mvn install
cd xboot-admin
mvn spring-boot:run

**Comment by Exrick** [comment]
请进入maven仓库删除xboot相关文件夹
