### ISSUE TITLE
源码阅读请教一个问题

### ISSUE THREAD

**Issue by yiyuan0109** [Exrick/xboot#47]
在debug 权限管理决断器(MyAccessDecisionManager),  看到authentication.getAuthorities() 权限操作集合里有角色的信息“ROLE_ADMIN” 这是在什么时候set的？
     
      @Override
      public void decide(Authentication authentication, Object o, Collection<ConfigAttribute> configAttributes) throws 
       AccessDeniedException, InsufficientAuthenticationException {
        if(configAttributes==null){
            return;
        }
        Iterator<ConfigAttribute> iterator = configAttributes.iterator();
        while (iterator.hasNext()){
            ConfigAttribute c = iterator.next();
            String needPerm = c.getAttribute();
              //authentication.getAuthorities() 权限操作集合里有角色的信息“ROLE_ADMIN” ?
            for(GrantedAuthority ga : authentication.getAuthorities()) {
                // 匹配用户拥有的ga 和 系统中的needPerm
                if(needPerm.trim().equals(ga.getAuthority())) {
                    return;
                }
            }
        }
        throw new AccessDeniedException("抱歉，您没有访问权限");
    }

**Comment by Exrick** [comment]
读取当前用户信息时 UserDetails
