### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by suny-yangke** [Exrick/xboot#49]
前端项目频繁需要needLogin，redis版本6.0.
尤其影响前端开发，几乎新建一个函数就得重新登录一次！！！

**Comment by Exrick** [comment]
应该是redis版本太新导致的异常，请根据引入的redis依赖客户端版本查看应使用的对应redis版本
目前spring-boot仅更新到对应redis 5.x版本

**Comment by suny-yangke** [comment]
非常感谢！

**Comment by Exrick** [comment]
怀疑是你多人开发导致的，默认配置开启单设备登录，单账号仅限一个设备登录，另外设备登录会挤掉！
最新代码已默认关闭该配置，详见配置文件！
